### ISSUE TITLE
Payment Page Return Blank

### ISSUE THREAD

**Issue by bewajijohnson** [bosunolanrewaju/WooCommerce-Flutterwave-Payment-Gateway#14]
Good day,

I signedup with flutterwave wand while makeing use of the flutterwave by using woocommerce plugin on the website mallbrisk.cemmey.com The payment transaction page returns blank error page.

I have used different versions of worpress to check through but its not working.

The ravepay woocommerce plugin is blank.

You can make a test run on the URL mallbrisk.cemmey.com

I await your response.

Thank you,

**Comment by bosunolanrewaju** [comment]
@bewajijohnson I just checked the website you shared. Looks like an issue not related to this plugin. Can you include the offline payment method in your WooCommerce setting and test to verify that the order page gets loaded properly?

**Comment by bewajijohnson** [comment]
@bosunolanrewaju I have included pay on delivery and it went fine with success.
Please kindly help melook at the issue. Kindly see the attachment for the error message I got when test from Local System. Its was when I got this error I decided, run it all from the web and still having error.

Effort will be much appreciated. Thanks.
![flutterwave_error](https://user-images.githubusercontent.com/34567398/34391084-0926d0e6-eb44-11e7-9cce-32780df93e4e.jpg)

**Comment by bosunolanrewaju** [comment]
@bewajijohnson What version of WooCommerce do you use?

**Comment by bewajijohnson** [comment]
@bosunolanrewaju Thank you for response. Am using WooCommerce Version 3.2.6

**Comment by bosunolanrewaju** [comment]
@bewajijohnson I have found the issue. It was introduced by a typo and I just made a fix.  
Download the update and test. Btw, thank you for reporting the issue and for your help in debugging it.

**Comment by bewajijohnson** [comment]
I appreciate your response and its working. I will like to PM you. Here is my Email: johnson.bewaji@cemmey.com
Please send me a blank mail and will take it from there.
Once again Thank you.
