### ISSUE TITLE
RavePay not working properly on my site

### ISSUE THREAD

**Issue by syncnd** [bosunolanrewaju/WooCommerce-Flutterwave-Payment-Gateway#16]
Hello Bosun,

I installed RavePay Woocommerce plugin on my Wordpress site, but the payment modal gets stuck at loading. After investigating, I discovered that the flutterwave inlinejs adds a 
```<div class="spinner-container"></div>``` and also a widget in my template also adds another ```<div class="spinner-container"></div>``` to my site ahead of the flutterwave inlinejs file. 

Therefore, the code 
`document.body.removeChild( document.getElementsByClassName('spinner-container')[0]);` 
throws an error 
`flwpbf-inline.js?ver=1.0.0:38 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
   at Object.message_handlers.allcontentloaded (https://api.ravepay.co/flwv3-pug/getpaidx/api/flwpbf-inline.js?ver=1.0.0:38:19)
   at https://api.ravepay.co/flwv3-pug/getpaidx/api/flwpbf-inline.js?ver=1.0.0:151:49` 
because there are more than one instance of ```.spinner``` and the first instance of ```.spinner-container``` is not a direct child of body. 

I suggest that you use an id at the very least instead, and also I dont think it is appropriate for the flwpbf-inline.js to manipulate my dom too.

**Comment by bosunolanrewaju** [comment]
@syncnd Thank you for reporting this. I agree with using `id` to target elements on the DOM. But, do know that this plugin is not responsible for the manipulation of the DOM. The payment modal, backdrop etc, are from the JS library `(flwpbf-inline.js`) provided by Ravepay.

I am cc'ing someone from the Ravepay team to help address this issue from the library.
cc @temiadesina

**Comment by bosunolanrewaju** [comment]
@syncnd I believe you have found a solution to the issue reported here as it is directly related to the JS library Ravepay provided and not the plugin. Hence, I am closing this issue.

**Comment by syncnd** [comment]
Yes, I did. Thanks.
