### ISSUE TITLE
I Need help understanding flutterwave docs

### ISSUE THREAD

**Issue by dawoodjee** [bosunolanrewaju/WooCommerce-Flutterwave-Payment-Gateway#17]
Hello Bosun

I'm trying hard to find the latest way to settle a payment in escrow and the docs seem to be outdated.

The [rave v2 docs clearly show](https://developer.flutterwave.com/v2.0/docs/escrow-payments#settling-an-escrow-payment) that the endpoint `https://api.ravepay.co/v2/gpx/transactions/escrow/settle` should settle a pending escrow payment, however, a 404 error comes up instead.

I've tried using `https://rave.flutterwave.com` and `https://ravesandbox.flutterwave.com`

No docs I can find show the right right way to settle escrow payment. Please help!

**Comment by bosunolanrewaju** [comment]
@dawoodjee Please reach out to Flutterwave for support
