### ISSUE TITLE
Charge Currency Setting

### ISSUE THREAD

**Issue by paulgeek** [bosunolanrewaju/WooCommerce-Flutterwave-Payment-Gateway#2]
can you add other currencies on the pay form. have my product price in usd, but on the pay form it shows only  NGN. pls help. I'm using rave checkout from access bank ghana. and my website is gkmcashew.Com
pls  help asap
![capture](https://cloud.githubusercontent.com/assets/27867379/25292649/999cbcdc-26c6-11e7-9bc3-715e04624e08.JPG)
![capture2](https://cloud.githubusercontent.com/assets/27867379/25292689/c365996c-26c6-11e7-99e9-52306c350064.JPG)

**Comment by bosunolanrewaju** [comment]
@paulgeek Please, can you use the latest master branch. I just added the currency and country option to the payment config object. So it uses the currency and country from your WooCommerce settings.

Let me know if it works.

**Comment by paulgeek** [comment]
Thanks in a million. its working now.

**Comment by paulgeek** [comment]
thanks in a million. its working now

**Comment by bosunolanrewaju** [comment]
You are welcome.
