### ISSUE TITLE
success-pending-validation

### ISSUE THREAD

**Issue by paulgeek** [bosunolanrewaju/WooCommerce-Flutterwave-Payment-Gateway#4]
im using woocommerce rave payment gateway on my site. and having problems on my transaction.  transaction status shows ''success-pending-validation'' and for days still showing same status. need help asap.
![z](https://cloud.githubusercontent.com/assets/27867379/25722376/e55de304-310b-11e7-80a8-7a5413b02576.JPG)
![zz1](https://cloud.githubusercontent.com/assets/27867379/25722391/f22aa91e-310b-11e7-83c8-1242389e4611.JPG)

**Comment by bosunolanrewaju** [comment]
@paulgeek I'd suggest that you talk to the support team at Rave about this issue because what you described has nothing to do with the plugin.

**Comment by paulgeek** [comment]
have talked to them and they have redirected me to the plugin again. hope it solves my problem now

**Comment by bosunolanrewaju** [comment]
Alright. But, like I said, this plugin has nothing to do with the issue. Have you been able to confirm that the currency your customers are charged with is allowed on your account?

**Comment by bosunolanrewaju** [comment]
@paulgeek have you been able to sort the issue with your account out? Closing this issue has it is not related to the functionalities provided by this plugin

**Comment by paulgeek** [comment]
Rave tech team are reviewing. i dont know how long it will take but its
pass a week now and they havent been able to solve it
