### ISSUE TITLE
Public Key Generation Issues

### ISSUE THREAD

**Issue by ugochiugb** [bosunolanrewaju/WooCommerce-Flutterwave-Payment-Gateway#7]
Hi There,

I have installed your awesome plugin in my wordpress site, created an account with flutterwave but I can't get a public key. I Tried to get it from the pay button a couple of times but it has been to no avail.

The parameters in the plugin settings do not tally with the keys on flutterwave. Please any assistance you can give me will be greatly appreciated.

Thanks

Ugochi

**Comment by bosunolanrewaju** [comment]
@ugochiugb Sorry for my late response. This plugin does not work with Flutterwave account's credentials, rather it works with Rave. Register for an account here: https://ravepay.co
