### ISSUE TITLE
System does not accept US Dollars from cards

### ISSUE THREAD

**Issue by hotsaq** [bosunolanrewaju/WooCommerce-Flutterwave-Payment-Gateway#8]
Please the ravepay payment gateway does not accept US Dollars from cards. We have tried several cards which we use to make purchases online and the system fail to accept USD with the cards. We need urgent help because our site is live in the market place.

**Comment by bosunolanrewaju** [comment]
@hotsaq This is an issue with your ravepay setup, so you should talk to the support team for assistance in setting up USD on your website.
