### ISSUE TITLE
Is it possible to NOT have the Bank Account tab show on the payment modal window?

### ISSUE THREAD

**Issue by emzola** [bosunolanrewaju/WooCommerce-Flutterwave-Payment-Gateway#9]
Is it possible to NOT have the Bank Account tab show on the payment modal window? I intend selling to the US audience and they are to pay by card only. Seeing a tab for bank account on the modal with unfamiliar banks will rather discourage than encourage them to buy. 

I tried to do this from my dashboard when creating a checkout button by setting the payment method as "Card Only", but didn't work. I realized this only works when using the inline embed method for the checkout button but doesn't work for the WooCommerce plugin.

**Comment by bosunolanrewaju** [comment]
Hmmmm, If it works on payment button from your dashboard, sure It can be integrated into the plugin. I will look at that use case and revert back to you.

**Comment by emzola** [comment]
Great! I will expect your update on this. Thanks a million in advance.

**Comment by bosunolanrewaju** [comment]
@emzola I just added the payment method option field to the Rave WooCommerce settings page. It should work as expected. Deactivate and delete the plugin from your website. Download from the master branch and install to confirm that it works.
